import time
import requests
from requests.api import request
f=open("config.txt",'w')
f.truncate(0)
f.close()
print("Thank you for installing Helium weather corolation data collection service")
time.sleep(.5)
print("Installing now")
time.sleep(.5)
address = str(input("Copy and paste your helium hotspot address here and hit enter: "))
time.sleep(.5)
key = str(input("Copy and paste your weather api key here and puch enter: "))
time.sleep(.5)
print("creating config.txt")
f=open("config.txt",'w')
f.write(address+"\n")
print("Added address")
location = (requests.request("GET","https://api.helium.io/v1/hotspots/"+address)).json()
f.write(str(round(location["data"]["lat"],6))+"\n"+str(round(location["data"]["lng"],6))+"\n"+str(key))
f.close()
time.sleep(.5)
print("Added location")
time.sleep(.2)
print("Added weather api key")
print("\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n\n")
print("Instialtion complete")